{% set version = "0.8.4" %}

package:
  name: pyrepl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyrepl/pyrepl-{{ version }}.tar.gz
  sha256: 3bcbbf1e47d2b80819b805aceea16dc90832ba4800035d595fa3c4bf48fcd4d7

build:
  number: 1002
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - ncurses

test:
  imports:
    - pyrepl

about:
  home: https://bitbucket.org/pypy/pyrepl
  license: MIT X11 style
  license_family: MIT
  license_file: LICENSE
  summary: 'A library for building flexible command line interfaces'

  description: |
    pyrepl is a Python library, inspired by readline, for building flexible
    command line interfaces, featuring:

     * sane multi-line editing
     * history, with incremental search
     * completion, including displaying of available options
     * a fairly large subset of the readline emacs-mode keybindings
     * a liberal, Python-style, license
     * a new python top-level.
  doc_url: https://bitbucket.org/pypy/pyrepl
  dev_url: https://bitbucket.org/pypy/pyrepl

extra:
  recipe-maintainers:
    - kynan
