# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangpython2.7
    - CONFIG=osx_c_compilerclangpython3.5
    - CONFIG=osx_c_compilerclangpython3.6
    - CONFIG=osx_c_compilerclangpython3.7
    - CONFIG=osx_c_compilertoolchain_cpython2.7
    - CONFIG=osx_c_compilertoolchain_cpython3.5
    - CONFIG=osx_c_compilertoolchain_cpython3.6
    - CONFIG=osx_c_compilertoolchain_cpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "GGHswdHqAPYvL8gqYR4twLWzXrrpCH8kDMuiz2iypxtPk72+mkd54PjQWPuKYo1PLJ/r0l7WJeQ0YgL3FAlysFXuFlPP/HRYMAZcA08rb4kgpM3NVIQYdSrlNwLxiGIWn3Mc1eTc9YCUIlcF5MAaoMkcEZXKsIWYVMD0Euz/RhKpwiE0N/fUi2x/t55o6GyG12WeVUIVpTpKYr/h/kpYdq4yond9XT0CqLh4M/6s6ao0sv3abp0Aoxvo6irR8tEVHdZ3Pk7XnkjVu4QS6Z2iTBHivK8pAAwvSQVNgByHUYS5pHL+SgMMLx5uRBeEAm1c2IMKzGZSSpnsZcoB1zNdd4ALy2xJdPIcnJclMGkK+Pj+CFqR2Kq3VlOxD8Ez75bEqF1EJ/Ap08HGktXgGjXQ6MuKxn5KhRWfXcitYy9TAKNq0kGCwjDboVPxpgmjO9Eu9Vwvd6kjKBNaRD798ggc/0di0YGPXNdJXu6Xo5C18Mj1KQXh9RBvbo6QHkNrUetoKx/N1rKbaKbXR9MRxCK1QZvmVF9y4FGJVj5dZeeKYIubZRBevvJLGscCscNAQdCP/4NNRifeMXSV3QNprfzLJMjf7IC+idFQXy9XLOUaAgdCHVAuwV2cPbIAPpDhqsZJvSFGN0tsjXTSCMFCS7twy3reeEZSB3eDbkm7PlhrqiI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
