travis:
  secure:
    BINSTAR_TOKEN: B3VV4F7L30PCPU0gaLSJ6ReZ4ZqZsoeH5uAgz83eYwu4LYsAGHOGUcWxusgokbQRVEB8D43GYpzX5kZB5+maBLST8rhVlddjo0vJwzajmH/USVVt5YUbFh0/FUvJHVlEb22cecvYKotrRxQ9Vb4mCjTiUH3PouVla3hS4NcbrkrBm97FBEnT0meSVJi5o0exG2zSEj4PpbpcvnfwqRn4LdLWSCmGij9fy0HN/SyoVcjotIaGR1f5FtoNVsdP8HLx9TnEZe2ZVmBuduOALTKVtZ4PH9rBLuH0XJwBKkd9dUuwk0ionAly6k8HOTwgSPOKpj+2SvMIwCPUwQKDt+Zdc2aRRbqIXiYDwbODb9oIdtQQJhwHP9QHeI6D1LSKfdrg7Fnxm2uwP6McNooZ7ysUei8BRXKJJuOzprvLDhY9faiPbTuMRvuHGTzkkEI98h28YdMuZQ7LfvFjIvX8kRzxxkJ1LA0bEM04b9I2G5dayWFmqssiCY8quf2VzzLVS/fRreesJvlTP7wSSJL0OaHOWcGSlLjFLAi5KH8NJBtnWTnTVGeqyHZ1JPeoedWJ1SCGHKf5728Qc5Re1dHB60LT7cFMugE/sigQdnwedXEvG7qZ3V/dFC3FOR/qZuldwmhi46rx9dd6fhgLeWKXM8nq7m9eDLlLDvZQ8XUlzPB3sJo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
