travis:
  secure:
    BINSTAR_TOKEN: GGHswdHqAPYvL8gqYR4twLWzXrrpCH8kDMuiz2iypxtPk72+mkd54PjQWPuKYo1PLJ/r0l7WJeQ0YgL3FAlysFXuFlPP/HRYMAZcA08rb4kgpM3NVIQYdSrlNwLxiGIWn3Mc1eTc9YCUIlcF5MAaoMkcEZXKsIWYVMD0Euz/RhKpwiE0N/fUi2x/t55o6GyG12WeVUIVpTpKYr/h/kpYdq4yond9XT0CqLh4M/6s6ao0sv3abp0Aoxvo6irR8tEVHdZ3Pk7XnkjVu4QS6Z2iTBHivK8pAAwvSQVNgByHUYS5pHL+SgMMLx5uRBeEAm1c2IMKzGZSSpnsZcoB1zNdd4ALy2xJdPIcnJclMGkK+Pj+CFqR2Kq3VlOxD8Ez75bEqF1EJ/Ap08HGktXgGjXQ6MuKxn5KhRWfXcitYy9TAKNq0kGCwjDboVPxpgmjO9Eu9Vwvd6kjKBNaRD798ggc/0di0YGPXNdJXu6Xo5C18Mj1KQXh9RBvbo6QHkNrUetoKx/N1rKbaKbXR9MRxCK1QZvmVF9y4FGJVj5dZeeKYIubZRBevvJLGscCscNAQdCP/4NNRifeMXSV3QNprfzLJMjf7IC+idFQXy9XLOUaAgdCHVAuwV2cPbIAPpDhqsZJvSFGN0tsjXTSCMFCS7twy3reeEZSB3eDbkm7PlhrqiI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
