travis:
  secure:
    BINSTAR_TOKEN: Kde402AMHfOOZHvsaVmKJPs1pbp4qOjrZHGYuhjHua/+oYt3hJoLxz224pf2RnkiPfUSRTUi/b55rfc5W6itAJYMuO4/Hoz8g4Op8zUUnLnmbR/BAlo95KlhMo4aN622b4+JRM8algv3KZGfnZuX3xlsVFE+RxRBIawBN2/6CJqaK1ByAxQLU5B0+VZsemc9MLTnhlcueTbI5IC38lqEafwyChQQmVnKpaikkBF8frLWRYzdyOqpujQfZx4b04Ou85zvs7L5QbcG3q0CeOErM4pybsmHfhG13gXQcsuqR5esR7/wyZkUb24Q6iTdDVfnMvuvFe/cB58klhZtk0YN+G6/i5MxR2wIVw5O/1UEF6TNo1DYmBxQ6FXX6l94QOfGfpgZ7XqJPK9X8IDaPT+jEriSEKq3y7CXoIL40AL0SGHJWmbrFA5X1Mis2tYYTcQfPYhq3ZG7tNmabCckHHrD8+J1rnhO0FNdVnDEptP1nANiYO4fhZxtfZu+rWpqXLYe4iGsBPo0OvKlKlmhOKIWudD2nxbMCNQxq4fAVYGkPNt4Dl9CV6Mz73TLVlXD/mkOqH5C7/e6+D5NRgyeqFHjFt4p3zLCZXTlbbCjPZkVLLMQrmQYWbcfZgdkm/w99OMnIU6rXKvOdjvpAPo+JGjZ/sFRBkEniMHdWplBSBx5fz4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
